base_url: "https://solomon.cloud.yandex-team.ru/api/v2"
project_id: "yc.iam.service-cloud"
method_duration_labels:
  sensor: grpc_durations|servlet_durations
  host: cluster
method_failrate_labels:
  sensor: grpc_statuses_total|servlet_statuses_total
  host: cluster

method_label_name:
  - method
