apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-load-test
spec:
  template:
    spec:
      containers:
      - name: math-worker
        # image: cr.yandex/crpsh8lqvs5nupoi3v85/iam-focal-build-axiom-jdk24:5
        image: cr.yandex/crp9j326k6up539jsjlm/iam-activeprobes:308612
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting calculation of factorial...";
            fact=1;
            for i in $(seq 1 100); do
              fact=$((fact * i));
            done;
            echo "Result: $fact";
      restartPolicy: Never
      nodeSelector:
        bootstrap.cloud.yandex.net/baseRole: iam-activeprobes
  backoffLimit: 0   # No retries on failure